const providers={
  opencode:{key:'opencode',serverId:'c7389bd0e731f80f49593e5ee53835475f4e28594dd6bd83eb229bab753498cd',async getConfig(){const [tab]=await chrome.tabs.query({active:true,lastFocusedWindow:true});let workspaceId=tab?.url?.match(/https:\/\/opencode\.ai\/workspace\/(wrk_[A-Za-z0-9]+)(?:\/|$)/)?.[1];if(workspaceId)await chrome.storage.local.set({opencodeWorkspaceId:workspaceId});else({opencodeWorkspaceId:workspaceId}=await chrome.storage.local.get('opencodeWorkspaceId'));if(!workspaceId)throw Error('请先打开一次 OpenCode 工作区用量页');if(!await chrome.cookies.get({url:'https://opencode.ai/',name:'auth'}))throw Error('未找到 OpenCode 登录信息');return{workspaceId}},async loadUsage({workspaceId}){const args={t:{t:9,i:0,l:1,a:[{t:1,s:workspaceId}],o:0},f:31,m:[]};const r=await fetch(`https://opencode.ai/_server?id=${this.serverId}&args=${encodeURIComponent(JSON.stringify(args))}`,{credentials:'include',headers:{'x-server-instance':'server-fn:3'}});if(!r.ok)throw Error(r.status===401||r.status===403?'登录状态已失效，请重新登录':`请求失败（${r.status}）`);return parseOpenCode(await r.text())}},
  command:{key:'command',async getConfig(){const session=await chrome.cookies.get({url:'https://api.commandcode.ai/',name:'__Secure-commandcode_prod_.session_token'});if(!session)throw Error('未找到 Command Code 登录信息，请先登录');return{}},async loadUsage(){const r=await fetch('https://api.commandcode.ai/internal/billing/credits',{credentials:'include',headers:{accept:'*/*'}});if(!r.ok)throw Error(r.status===401||r.status===403?'登录状态已失效，请重新登录':`请求失败（${r.status}）`);return parseCommand(await r.json())}}
};
const refreshButton=document.querySelector('#refresh'),WARN=60,HIGH=80;
function tone(p){return p>=HIGH?'high':p>=WARN?'warn':'ok'}
function remain(s){const v=Number(s);if(!Number.isFinite(v)||v<=0)return'重置时间未知';const d=Math.floor(v/86400),h=Math.floor(v%86400/3600),m=Math.max(1,Math.floor(v%3600/60));return d?`将在 ${d} 天 ${h} 小时后重置`:h?`将在 ${h} 小时 ${m} 分钟后重置`:`将在 ${m} 分钟后重置`}
function remainUntil(timestamp){return remain((Number(timestamp)-Date.now())/1000)}
function status(k,t,s){const e=document.querySelector(`#status-${k}`);e.textContent=t;e.className=`status ${s}`}
function render(k,items){const list=document.querySelector(`#usage-list-${k}`);list.replaceChildren(...items.map(x=>{const p=Math.max(0,Math.min(100,Number(x.usagePercent)||0)),detail=x.detail ?? (x.noBar?'':remain(x.resetInSec)),e=document.createElement('div');e.className=`usage-item tone-${tone(p)}${x.noBar?' no-bar':''}`;e.innerHTML=`<div class="usage-label"><span>${x.label}</span><strong>${x.valueText||`${p.toFixed(p%1?1:0)}%`}</strong></div>${x.noBar?'':`<div class="track"><div class="fill" style="width:${p}%"></div></div>`}${detail||x.detailRight?`<div class="usage-meta">${detail?`<small>${detail}</small>`:''}${x.detailRight?`<small>${x.detailRight}</small>`:''}</div>`:''}`;return e}))}
function error(k,msg){status(k,'失败','error');document.querySelector(`#usage-list-${k}`).replaceChildren();document.querySelector(`#error-message-${k}`).textContent=msg;document.querySelector(`#error-${k}`).hidden=false}
function parseOpenCode(text){const labels={rollingUsage:'🔄 滚动用量',weeklyUsage:'📅 每周用量',monthlyUsage:'🗓️ 每月用量'},out=[];for(const[k,label]of Object.entries(labels)){let s=new RegExp(`${k}:\\s*\\{([\\s\\S]*?)\\}`,'m').exec(text)?.[1];if(!s){const ref=new RegExp(`${k}:\\s*\\$R\\[(\\d+)\\]`).exec(text)?.[1];if(ref)s=new RegExp(`\\$R\\[${ref}\\]\\s*=\\s*\\{([\\s\\S]*?)\\}`,'m').exec(text)?.[1]}const p=/usagePercent:\s*([0-9.]+)/.exec(s||'')?.[1],r=/resetInSec:\s*([0-9.]+)/.exec(s||'')?.[1];if(p!==undefined&&r!==undefined)out.push({label,usagePercent:p,resetInSec:r})}if(out.length!==3)throw Error('接口返回格式异常');return out}
function parseCommand(d){const w=d?.windowLimits,c=d?.credits;if(!w?.fiveHour||!w?.weekly||!c)throw Error('接口返回格式异常');return[{label:'⏱ 5 小时窗口',usagePercent:w.fiveHour.used/w.fiveHour.cap*100,valueText:`${(w.fiveHour.used/w.fiveHour.cap*100).toFixed(1)}%`,detail:remainUntil(w.fiveHour.resetAt),detailRight:`${w.fiveHour.used.toFixed(2)} / ${w.fiveHour.cap}`},{label:'📅 每周窗口',usagePercent:w.weekly.used/w.weekly.cap*100,valueText:`${(w.weekly.used/w.weekly.cap*100).toFixed(1)}%`,detail:remainUntil(w.weekly.resetAt),detailRight:`${w.weekly.used.toFixed(2)} / ${w.weekly.cap}`},{label:'✦ 月度积分余额',noBar:true,valueText:Number(c.monthlyCredits).toFixed(2)} ]}
async function load(p){status(p.key,'加载中','loading');try{document.querySelector(`#error-${p.key}`).hidden=true;render(p.key,await p.loadUsage(await p.getConfig()));status(p.key,'正常','ok')}catch(e){error(p.key,e.message||'加载失败')}}
async function refresh(){if(refreshButton.disabled)return;refreshButton.disabled=true;await Promise.all(Object.values(providers).map(load));document.querySelector('#updated-at').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});refreshButton.disabled=false}
refreshButton.addEventListener('click',refresh);refresh();
